name: All Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 16, 18, 20, 22 ]

    name: Using Node.js v${{ matrix.node }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: make prepare-package

      - name: Run Tests
        run: |
          output=$(DEBUG_LEVEL=trace make test | tee >(cat >&2));
          if [ ${PIPESTATUS[0]} -ne 0 ]; then exit ${PIPESTATUS[0]}; fi
          passing=$(echo "$output" | grep -oP '\d+ passing' | grep -oP '\d+' | awk '{sum+=$1} END {print sum}')
          failing=$(echo "$output" | grep -oP '\d+ failing' | grep -oP '\d+' | awk '{sum+=$1} END {print sum}')
          pending=$(echo "$output" | grep -oP '\d+ pending' | grep -oP '\d+' | awk '{sum+=$1} END {print sum}')
          echo "## Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Node.js            | Passed   | Failed   | Pending  |" >> $GITHUB_STEP_SUMMARY
          echo "|--------------------|----------|----------|----------|" >> $GITHUB_STEP_SUMMARY
          echo "| ${{ matrix.node }} | $passing | $failing | $pending |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
